version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    expose:
      - "80"
    restart: always
    container_name: nginx
    volumes:
    - "./www:/usr/share/nginx/html:ro"
    - "./log:/var/log/nginx"
    - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    environment:
      VIRTUAL_HOST: "cedruyne.test"

networks:
  default:
    external:
      name: nginx-proxy